env:
  DEBIAN_FRONTEND: "noninteractive"

steps:
  - label: ":test_tube: Validate R Code"
    key: "validate"
    agents:
      queue: "buildkite-queue"
    command: .buildkite/scripts/validate.sh
    plugins:
      - docker#v5.12.0:
          image: "ubuntu:24.04"
          environment:
            - "DEBIAN_FRONTEND=noninteractive"
