# ============================================================================
# Translated from: Validate R Code
# ============================================================================
#
# TRIGGERS:
#   - push: branches [main]
#   - pull_request: branches [main]
#   - workflow_dispatch (manual trigger via "New Build" button in Buildkite UI)
#
# Configure in Buildkite UI → Pipeline Settings → GitHub:
#   - Enable "Build pull requests"
#   - Enable "Build branches" (filter: main)
#
# ============================================================================
#
# AGENT CONFIGURATION REQUIRED
# ============================================================================
# The original workflow used the following GitHub Actions runner:
#
#   Job                  | runs-on
#   ---------------------|----------------
#   validate             | ubuntu-24.04
#
# You must configure Buildkite agents to handle this workload. Add an
# `agents` block to the step once your queue is set up. Example:
#
#   agents:
#     queue: "linux"
#
# Required tools on agents: R, make, apt package management
# Alternatively, use the Docker plugin with ubuntu:24.04 image.
#
# NOTE: This pipeline performs extensive system-level package installation
# (R, r2u repository, bspm, system dependencies). Consider:
#   1. Pre-installing R and dependencies on agents, OR
#   2. Using a Docker image with R pre-configured, OR
#   3. Creating a custom agent AMI/image with the R environment
#
# ============================================================================

env:
  DEBIAN_FRONTEND: "noninteractive"

steps:
  - label: ":test_tube: Validate R Code"
    key: "validate"
    agents:
      queue: "buildkite-queue"
    command: .buildkite/scripts/validate.sh
    plugins:
      - docker#v5.12.0:
          image: "ubuntu:24.04"
          environment:
            - "DEBIAN_FRONTEND=noninteractive"
